import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase';

interface MasterSeed {
  sections?: Array<{
    type: string;
    content: string;
    styles?: Record<string, string>;
  }>;
  styles?: Record<string, string>;
  pages?: Array<{
    path: string;
    content: string;
  }>;
  [key: string]: any;
}

interface PublishRequest {
  project_id: string;
  master_seed: MasterSeed;
  zone_type: string;
}

/**
 * Converts master_seed sections into HTML/CSS files for deployment
 */
function buildHTMLFilesFromSeed(master_seed: MasterSeed): Array<{ file: string; data: string }> {
  const files: Array<{ file: string; data: string }> = [];

  // Generate index.html
  const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Zyntrix Project</title>
  <link rel="stylesheet" href="/styles.css">
</head>
<body>
  ${master_seed.sections?.map(section => `
  <section class="section-${section.type}">
    ${section.content}
  </section>
  `).join('\n') || '<div>Generated by Zyntrix</div>'}
</body>
</html>
  `.trim();

  files.push({
    file: 'index.html',
    data: htmlContent
  });

  // Generate styles.css
  const cssContent = `
/* Global Styles */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
  line-height: 1.6;
  color: #333;
}

${master_seed.sections?.map((section, index) => `
.section-${section.type} {
  padding: 2rem;
  ${section.styles ? Object.entries(section.styles).map(([key, value]) => `${key}: ${value};`).join('\n  ') : ''}
}
`).join('\n') || ''}

${master_seed.styles ? Object.entries(master_seed.styles).map(([selector, styles]) => {
  return `${selector} { ${typeof styles === 'object' ? Object.entries(styles).map(([k, v]) => `${k}: ${v};`).join(' ') : styles} }`;
}).join('\n\n') : ''}
  `.trim();

  files.push({
    file: 'styles.css',
    data: cssContent
  });

  // Add additional pages if defined
  if (master_seed.pages) {
    master_seed.pages.forEach(page => {
      files.push({
        file: page.path,
        data: page.content
      });
    });
  }

  return files;
}

/**
 * POST /api/publish
 * Handles publishing projects to Vercel
 */
export async function POST(req: NextRequest) {
  try {
    const body: PublishRequest = await req.json();
    const { project_id, master_seed, zone_type } = body;

    // Validate required fields
    if (!project_id || !master_seed || !zone_type) {
      return NextResponse.json(
        { error: 'Missing required fields: project_id, master_seed, zone_type' },
        { status: 400 }
      );
    }

    // Handle website and SaaS deployments
    if (zone_type === 'website' || zone_type === 'saas') {
      // Check for Vercel token
      if (!process.env.VERCEL_TOKEN) {
        return NextResponse.json(
          { error: 'VERCEL_TOKEN not configured' },
          { status: 500 }
        );
      }

      // Build HTML files from master seed
      const files = buildHTMLFilesFromSeed(master_seed);

      // Deploy to Vercel
      const vercelResponse = await fetch('https://api.vercel.com/v13/deployments', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${process.env.VERCEL_TOKEN}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          name: `zyntrix-${project_id}`,
          files: files,
          projectSettings: { 
            framework: null,
            buildCommand: null,
            outputDirectory: null
          }
        })
      });

      if (!vercelResponse.ok) {
        const error = await vercelResponse.text();
        console.error('Vercel deployment failed:', error);
        return NextResponse.json(
          { error: 'Deployment failed', details: error },
          { status: vercelResponse.status }
        );
      }

      const deploy = await vercelResponse.json();
      const deployedUrl = `https://${deploy.url}`;

      // Update project in database
      const supabase = createClient();
      const { error: updateError } = await supabase
        .from('projects')
        .update({ deployed_url: deployedUrl })
        .eq('id', project_id);

      if (updateError) {
        console.error('Failed to update project with deployed URL:', updateError);
        // Don't fail the deployment if DB update fails
      }

      return NextResponse.json({ 
        url: deployedUrl, 
        project_id,
        deployment_id: deploy.id,
        success: true
      });
    }

    // Handle other zone types
    return NextResponse.json(
      { error: `Zone type "${zone_type}" is not yet supported` },
      { status: 400 }
    );

  } catch (error) {
    console.error('Publish API error:', error);
    return NextResponse.json(
      { error: 'Internal server error', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    );
  }
}
