/**
 * /api/export-game
 *
 * Accepts: POST { project_id: string }
 *   OR:    GET  ?project_id=<uuid>
 *
 * Fetches the project's master_director_seed from Supabase, then builds a ZIP
 * containing:
 *   godot_seed.json     — full director seed (world / characters / narrative)
 *   project.godot       — minimal Godot 4 project descriptor
 *   World.gd            — GDScript bootstrap that reads godot_seed.json at runtime
 *   export_presets.cfg  — template export preset for Windows / Linux / Web
 *   README.md           — step-by-step guide: open in Godot → tweak → export EXE
 *
 * The GDScript reads the seed file at runtime so designers can tweak values
 * without touching code — just edit godot_seed.json and re-run.
 */

import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import JSZip from "jszip";

// ─── Types ────────────────────────────────────────────────────────────────────

interface CharacterSeed {
  id: string;
  role: string;
  appearance_seed: number;
  [key: string]: unknown;
}

interface WorldSeed {
  biome?: string;
  time_of_day?: number;
  weather?: string;
  [key: string]: unknown;
}

interface MasterDirectorSeed {
  project_name?: string;
  world?: WorldSeed;
  characters?: CharacterSeed[];
  narrative?: Record<string, unknown>;
  [key: string]: unknown;
}

// ─── GDScript bootstrap ───────────────────────────────────────────────────────

function buildWorldGd(name: string): string {
  return `extends Node

## World.gd — auto-generated by TailAdmin Game Export
## Reads godot_seed.json at startup and applies it to the scene.
##
## HOW TO EXTEND:
##   1. Open the Godot editor.
##   2. Attach this script to your root scene node (e.g. "World").
##   3. Edit godot_seed.json to change biome, characters, and narrative parameters.
##   4. The seed is re-read every time the game launches (hot-reload in editor).

const SEED_PATH := "res://godot_seed.json"

var seed_data: Dictionary = {}

func _ready() -> void:
\tvar file := FileAccess.open(SEED_PATH, FileAccess.READ)
\tif file:
\t\tvar json := JSON.new()
\t\tjson.parse(file.get_as_text())
\t\tseed_data = json.get_data()
\t\tfile.close()
\t\t_apply_seed()
\t\tprint("[${name}] Seed loaded: ", seed_data.get("project_name", "unnamed"))
\telse:
\t\tpush_error("[${name}] Could not open godot_seed.json at: " + SEED_PATH)

func _apply_seed() -> void:
\tvar world: Dictionary = seed_data.get("world", {})
\tvar characters: Array  = seed_data.get("characters", [])
\tvar narrative: Dictionary = seed_data.get("narrative", {})

\t# ── World ────────────────────────────────────────────────────────────────
\t# TODO: swap out your Environment / WorldEnvironment based on world.biome
\tvar biome: String  = world.get("biome", "forest")
\tvar tod: float     = float(world.get("time_of_day", 12))
\tvar weather: String = world.get("weather", "clear")
\tprint("  biome=%s  time=%s  weather=%s" % [biome, tod, weather])

\t# ── Characters ───────────────────────────────────────────────────────────
\tfor char_data in characters:
\t\tvar char_id: String     = char_data.get("id", "unknown")
\t\tvar role: String        = char_data.get("role", "extra")
\t\tvar seed_val: float     = float(char_data.get("appearance_seed", 0.5))
\t\tprint("  char=%s  role=%s  seed=%.3f" % [char_id, role, seed_val])
\t\t# TODO: instantiate character scenes and set their appearance from seed_val

\t# ── Narrative ────────────────────────────────────────────────────────────
\tvar act: int       = int(narrative.get("act", 1))
\tvar tension: float = float(narrative.get("tension", 0.5))
\tprint("  act=%d  tension=%.2f" % [act, tension])
\t# TODO: trigger quest events / AI dialogue based on act + tension
`;
}

function buildProjectGodot(name: string): string {
  const safeId = name.toLowerCase().replace(/\s+/g, "_").replace(/[^a-z0-9_]/g, "");
  return `; Engine configuration file — Godot 4.x
; Exported by TailAdmin Game Studio

[application]
config/name="${name}"
config/version="1.0"
run/main_scene="res://World.tscn"

[editor]
run/main_run_args=""

[filesystem]
import/blender/enabled=false

[physics]
common/physics_engine="GodotPhysics3D"

[rendering]
renderer/rendering_method="forward_plus"
environment/defaults/default_clear_color=Color(0.1, 0.1, 0.1, 1)

[project_settings_override]
application/config/project_data_path="res://.godot"
application/config/project_name="${safeId}"
`;
}

function buildExportPresets(name: string): string {
  const safeName = name.replace(/[^a-zA-Z0-9_ ]/g, "").trim() || "game";
  return `[preset.0]
name="Windows Desktop"
platform="Windows Desktop"
runnable=true
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="export/${safeName}.exe"
encryption_include_filters=""
encryption_exclude_filters=""
script_export_mode=1

[preset.0.options]
custom_template/debug=""
custom_template/release=""
binary_format/64_bits=true
binary_format/embed_pck=false

[preset.1]
name="Linux/X11"
platform="Linux/X11"
runnable=true
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="export/${safeName}.x86_64"
encryption_include_filters=""
encryption_exclude_filters=""
script_export_mode=1

[preset.2]
name="Web"
platform="Web"
runnable=false
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="export/web/index.html"
script_export_mode=1
`;
}

function buildReadme(name: string, seed: MasterDirectorSeed): string {
  const biome   = seed.world?.biome ?? "forest";
  const chars   = (seed.characters ?? []).map(c => `- **${c.id}** (${c.role})`).join("\n");
  return `# ${name} — Godot 4 Export

Auto-generated by **TailAdmin Game Studio**.

## 📁 Files

| File | Purpose |
|------|---------|
| \`godot_seed.json\` | Full director seed — edit to change world & characters |
| \`project.godot\` | Godot 4 project descriptor — open this in the editor |
| \`World.gd\` | GDScript bootstrap — reads the seed at runtime |
| \`export_presets.cfg\` | Pre-configured export targets (Windows / Linux / Web) |

## 🚀 Quick Start

### 1. Install Godot 4

Download from <https://godotengine.org/download/>

### 2. Open the project

\`\`\`bash
godot4 --editor project.godot
\`\`\`

Or launch the Godot editor → **Import** → select \`project.godot\`.

### 3. Create a root scene

1. **Scene → New Scene**
2. Add a **Node3D** root node (rename to "World")
3. Attach **World.gd** as its script
4. Save as **World.tscn**

### 4. Export as EXE (Windows)

1. **Project → Export…**
2. Select the **Windows Desktop** preset (already configured in \`export_presets.cfg\`)
3. Click **Export Project** → choose an output directory
4. Run \`export/${name}.exe\`

### 5. Export for Web (HTML5)

Use the **Web** preset — output goes to \`export/web/index.html\`.
Serve with any static host (Netlify, Vercel, itch.io).

## 🌍 Seed Summary

**World:** biome \`${biome}\`, time ${seed.world?.time_of_day ?? 12}h, weather \`${seed.world?.weather ?? "clear"}\`

**Characters:**
${chars || "- none defined"}

**Narrative:** act ${seed.narrative?.act ?? 1}, tension ${seed.narrative?.tension ?? 0.4}

Edit \`godot_seed.json\` and restart the game to apply changes without recompiling.
`;
}

// ─── Route handler ────────────────────────────────────────────────────────────

async function getProjectId(req: NextRequest): Promise<string | null> {
  if (req.method === "GET") return req.nextUrl.searchParams.get("project_id");
  try { return (await req.json())?.project_id ?? null; } catch { return null; }
}

export async function GET(req: NextRequest)  { return handler(req); }
export async function POST(req: NextRequest) { return handler(req); }

async function handler(req: NextRequest) {
  const projectId = await getProjectId(req);
  if (!projectId) {
    return NextResponse.json({ error: "project_id is required" }, { status: 400 });
  }

  const sb = await createClient();
  const { data: project, error } = await sb
    .from("projects")
    .select("id, type, master_director_seed")
    .eq("id", projectId)
    .single();

  if (error || !project) {
    return NextResponse.json({ error: "Project not found" }, { status: 404 });
  }

  if (project.type !== "game") {
    return NextResponse.json(
      { error: `Project type is "${project.type}", expected "game"` },
      { status: 400 }
    );
  }

  const seed = (project.master_director_seed ?? {}) as MasterDirectorSeed;
  const name = seed.project_name ?? "My Game";
  const slug = name.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");

  const zip = new JSZip();

  zip.file("godot_seed.json",     JSON.stringify(seed, null, 2));
  zip.file("project.godot",       buildProjectGodot(name));
  zip.file("World.gd",            buildWorldGd(name));
  zip.file("export_presets.cfg",  buildExportPresets(name));
  zip.file("README.md",           buildReadme(name, seed));

  // Placeholder scene — users replace with real .tscn content
  zip.file(
    "World.tscn",
    `[gd_scene load_steps=1 format=3 uid="uid://world_placeholder"]

[node name="World" type="Node3D"]
script = ExtResource("res://World.gd")
`
  );

  const buffer = await zip.generateAsync({ type: "nodebuffer" });

  return new Response(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="${slug}-godot.zip"`,
      "Content-Length": String(buffer.length),
    },
  });
}
